version = 0.1

[default.deploy.parameters]
stack_name = "riot-notifier"
resolve_s3 = true
s3_prefix = "riot-notifier"
region = "us-east-1"
capabilities = "CAPABILITY_IAM"
parameter_overrides = "RiotApiKey=\"CHANGE_ME\" SesSenderEmail=\"CHANGE_ME\""
